# Generated by Django 6.0 on 2026-01-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
