# Generated by Django 6.0 on 2026-01-06 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_foto_alter_aluno_cpf_alter_aluno_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
            options={
                'unique_together': {('aluno', 'data_aula')},
            },
        ),
    ]
