# Generated by Django 6.0 on 2026-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='trancada',
            field=models.BooleanField(default=False),
        ),
    ]
