# Generated by Django 6.0 on 2026-02-18 22:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_matricula_trancada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor_hex', models.CharField(default='#CCCCCC', help_text='Cor em Hexadecimal (ex: #FF0000)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ContaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Conta')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Previsto (R$)')),
                ('dia_vencimento', models.PositiveIntegerField(verbose_name='Dia de Vencimento (1-31)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriagasto')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Gasto')),
                ('pago', models.BooleanField(default=True, verbose_name='Pago?')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriagasto', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência (Dia 1)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Real')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('conta_fixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.contafixa')),
            ],
            options={
                'unique_together': {('conta_fixa', 'mes_referencia')},
            },
        ),
    ]
