# Generated by Django 6.0 on 2026-02-19 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoriagasto_contafixa_gasto_faturamensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cobranca', 'Cobrança'), ('presenca', 'Falta/Presença'), ('aviso_geral', 'Aviso Geral'), ('parabens', 'Parabéns/Graduação')], default='cobranca', max_length=50)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('enviado_por', models.CharField(default='Jarbas', help_text='Quem enviou (Jarbas ou Sistema)', max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.aluno')),
            ],
        ),
    ]
